# Generated by Django 3.1.1 on 2020-09-03 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200903_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='imagen_refencial',
            new_name='imagen_referencial',
        ),
    ]
