# Generated by Django 3.1.1 on 2020-09-06 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200903_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='apellidos',
            field=models.CharField(blank=True, max_length=120, verbose_name='Apellidos'),
        ),
    ]
